### ISSUE TITLE
Windows 7 build?

### ISSUE THREAD

**Issue by DruggedBunny** [izzyreal/mpc#117]
I'm wondering if a Windows 7 build could be provided, as mentioned on the main site? I've attempted to do it myself with the workspace version but although I found the win7 workspace build option and installed all the dependencies, it eventually failed for me (says 'Exception: Command failed: cmake .. -G "Visual Studio 17 2022" -DVMPC2000XL_WIN7=1')... and I'm not a proper developer!

Only if it's not too much work, of course... I've never tried a real MPC, but have always wondered if the workflow would suit me... and the project just looks really cool, so I'm just curious to try it. (I'm on 64-bit Win7 but can make use of either 32 or 64-bit executable or VST.)

Thank you -- no worries if not!

**Comment by DruggedBunny** [comment]
No problem, I've gone through vmpc-workspace instructions up to:

> If you want to use Visual Studio and build 64 bit binaries, run
> python build.py vs

... but replaced that with:

> python build-workspace.py vs2022-win7

... the result being below -- I've just spotted this, so probably relevant!

> CMake Error: Could not create named generator Visual Studio 17 2022

Also refers to 'compiler.version=15' but I'm not sure how/where that's set up, or if it's even directly relevant to "Visual Studio 17 2022" (don't understand the version system they use at all!) -- I actually installed the very latest VS last night and rebooted prior to running the build.

Hope this helps!

```

Already up to date.
D:\Sources\Python Sources\vmpc\vmpc-workspace\akaifat
Already up to date.
D:\Sources\Python Sources\vmpc\vmpc-workspace\moduru
Already up to date.
D:\Sources\Python Sources\vmpc\vmpc-workspace\ctoot
Already up to date.
D:\Sources\Python Sources\vmpc\vmpc-workspace\mpc
Already up to date.
D:\Sources\Python Sources\vmpc\vmpc-workspace\vmpc-juce
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=15
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

Requirements
    catch2/2.13.8 from 'conancenter' - Cache
    ghc-filesystem/1.4.0 from 'conancenter' - Cache
    juce/0.1@izmar/dev from 'jfrog-izmar' - Cache
    rapidjson/1.1.0 from 'conancenter' - Cache
    tl-expected/20190710 from 'conancenter' - Cache
    akaifat/0.1@izmar/dev from user folder - Editable
    ctoot/0.1@izmar/dev from user folder - Editable
    moduru/0.1@izmar/dev from user folder - Editable
    mpc/0.1@izmar/dev from user folder - Editable
    vmpc-juce/0.1@izmar/dev from user folder - Editable
Packages
    catch2/2.13.8:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache
    ghc-filesystem/1.4.0:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache
    juce/0.1@izmar/dev:6c6d4a9cf35f9c599858220dd6e2d3951493b05f - Cache
    rapidjson/1.1.0:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache
    tl-expected/20190710:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache
    akaifat/0.1@izmar/dev:d6029dc74ed011fc2985ec64057d4f39861e2eaa - Editable
    ctoot/0.1@izmar/dev:4cfc965431eb7db9333b8f18f8f662993f833f48 - Editable
    moduru/0.1@izmar/dev:4cab410d882df02443868d4362ea1c1c212052f6 - Editable
    mpc/0.1@izmar/dev:3aa1dc05957add989e1fcf6d2b3a281b8b15a194 - Editable
    vmpc-juce/0.1@izmar/dev:108b1c06e9aaa65f22d4ac19af4859d0f6600068 - Editable

Installing (downloading, building) binaries...
catch2/2.13.8: Already installed!
ghc-filesystem/1.4.0: Already installed!
juce/0.1@izmar/dev: Already installed!
rapidjson/1.1.0: Already installed!
tl-expected/20190710: Already installed!
akaifat/0.1@izmar/dev: Generator cmake created conanbuildinfo.cmake
akaifat/0.1@izmar/dev: Aggregating env generators
akaifat/0.1@izmar/dev: Generated conaninfo.txt
akaifat/0.1@izmar/dev: Generated graphinfo
akaifat/0.1@izmar/dev: Generated conanbuildinfo.txt
moduru/0.1@izmar/dev: Generator cmake created conanbuildinfo.cmake
moduru/0.1@izmar/dev: Aggregating env generators
moduru/0.1@izmar/dev: Generated conaninfo.txt
moduru/0.1@izmar/dev: Generated graphinfo
moduru/0.1@izmar/dev: Generated conanbuildinfo.txt
ctoot/0.1@izmar/dev: Generator cmake created conanbuildinfo.cmake
ctoot/0.1@izmar/dev: Aggregating env generators
ctoot/0.1@izmar/dev: Generated conaninfo.txt
ctoot/0.1@izmar/dev: Generated graphinfo
ctoot/0.1@izmar/dev: Generated conanbuildinfo.txt
mpc/0.1@izmar/dev: Generator cmake created conanbuildinfo.cmake
mpc/0.1@izmar/dev: Aggregating env generators
mpc/0.1@izmar/dev: Generated conaninfo.txt
mpc/0.1@izmar/dev: Generated graphinfo
mpc/0.1@izmar/dev: Generated conanbuildinfo.txt
vmpc-juce/0.1@izmar/dev: Generator cmake_paths created conan_paths.cmake
vmpc-juce/0.1@izmar/dev: Generator cmake created conanbuildinfo.cmake
vmpc-juce/0.1@izmar/dev: Aggregating env generators
vmpc-juce/0.1@izmar/dev: Generated conaninfo.txt
vmpc-juce/0.1@izmar/dev: Generated graphinfo
vmpc-juce/0.1@izmar/dev: Generated conanbuildinfo.txt
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=Visual Studio
compiler.runtime=MDd
compiler.version=15
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

Requirements
    catch2/2.13.8 from 'conancenter' - Cache
    ghc-filesystem/1.4.0 from 'conancenter' - Cache
    juce/0.1@izmar/dev from 'jfrog-izmar' - Cache
    rapidjson/1.1.0 from 'conancenter' - Cache
    tl-expected/20190710 from 'conancenter' - Cache
    akaifat/0.1@izmar/dev from user folder - Editable
    ctoot/0.1@izmar/dev from user folder - Editable
    moduru/0.1@izmar/dev from user folder - Editable
    mpc/0.1@izmar/dev from user folder - Editable
    vmpc-juce/0.1@izmar/dev from user folder - Editable
Packages
    catch2/2.13.8:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache
    ghc-filesystem/1.4.0:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache
    juce/0.1@izmar/dev:bd41d6960c74b8b55bb9d01c8d1724907962aa67 - Cache
    rapidjson/1.1.0:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache
    tl-expected/20190710:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache
    akaifat/0.1@izmar/dev:3f5e11951023ee31c72766ce365fd2d94eb3a5f3 - Editable
    ctoot/0.1@izmar/dev:c181a5cf4737a690b0ba0f3206116628e0e774fd - Editable
    moduru/0.1@izmar/dev:26aec98ef3f87f30409c206fbb2350b90b3728fb - Editable
    mpc/0.1@izmar/dev:f9a4f55382508b4737ce0ef6a6f2b8b1fa990065 - Editable
    vmpc-juce/0.1@izmar/dev:5291d35c496fb7a3581a578e57a6b90578a29d86 - Editable

Installing (downloading, building) binaries...
catch2/2.13.8: Already installed!
ghc-filesystem/1.4.0: Already installed!
juce/0.1@izmar/dev: Already installed!
rapidjson/1.1.0: Already installed!
tl-expected/20190710: Already installed!
akaifat/0.1@izmar/dev: Generator cmake created conanbuildinfo.cmake
akaifat/0.1@izmar/dev: Aggregating env generators
akaifat/0.1@izmar/dev: Generated conaninfo.txt
akaifat/0.1@izmar/dev: Generated graphinfo
akaifat/0.1@izmar/dev: Generated conanbuildinfo.txt
moduru/0.1@izmar/dev: Generator cmake created conanbuildinfo.cmake
moduru/0.1@izmar/dev: Aggregating env generators
moduru/0.1@izmar/dev: Generated conaninfo.txt
moduru/0.1@izmar/dev: Generated graphinfo
moduru/0.1@izmar/dev: Generated conanbuildinfo.txt
ctoot/0.1@izmar/dev: Generator cmake created conanbuildinfo.cmake
ctoot/0.1@izmar/dev: Aggregating env generators
ctoot/0.1@izmar/dev: Generated conaninfo.txt
ctoot/0.1@izmar/dev: Generated graphinfo
ctoot/0.1@izmar/dev: Generated conanbuildinfo.txt
mpc/0.1@izmar/dev: Generator cmake created conanbuildinfo.cmake
mpc/0.1@izmar/dev: Aggregating env generators
mpc/0.1@izmar/dev: Generated conaninfo.txt
mpc/0.1@izmar/dev: Generated graphinfo
mpc/0.1@izmar/dev: Generated conanbuildinfo.txt
vmpc-juce/0.1@izmar/dev: Generator cmake_paths created conan_paths.cmake
vmpc-juce/0.1@izmar/dev: Generator cmake created conanbuildinfo.cmake
vmpc-juce/0.1@izmar/dev: Aggregating env generators
vmpc-juce/0.1@izmar/dev: Generated conaninfo.txt
vmpc-juce/0.1@izmar/dev: Generated graphinfo
vmpc-juce/0.1@izmar/dev: Generated conanbuildinfo.txt
CMake Error: Could not create named generator Visual Studio 17 2022

Generators
  Visual Studio 16 2019        = Generates Visual Studio 2019 project files.
                                 Use -A option to specify architecture.
* Visual Studio 15 2017 [arch] = Generates Visual Studio 2017 project files.
                                 Optional [arch] can be "Win64" or "ARM".
  Visual Studio 14 2015 [arch] = Generates Visual Studio 2015 project files.
                                 Optional [arch] can be "Win64" or "ARM".
  Visual Studio 12 2013 [arch] = Generates Visual Studio 2013 project files.
                                 Optional [arch] can be "Win64" or "ARM".
  Visual Studio 11 2012 [arch] = Generates Visual Studio 2012 project files.
                                 Optional [arch] can be "Win64" or "ARM".
  Visual Studio 10 2010 [arch] = Generates Visual Studio 2010 project files.
                                 Optional [arch] can be "Win64" or "IA64".
  Visual Studio 9 2008 [arch]  = Generates Visual Studio 2008 project files.
                                 Optional [arch] can be "Win64" or "IA64".
  Borland Makefiles            = Generates Borland makefiles.
  NMake Makefiles              = Generates NMake makefiles.
  NMake Makefiles JOM          = Generates JOM makefiles.
  MSYS Makefiles               = Generates MSYS makefiles.
  MinGW Makefiles              = Generates a make file for use with
                                 mingw32-make.
  Unix Makefiles               = Generates standard UNIX makefiles.
  Green Hills MULTI            = Generates Green Hills MULTI files
                                 (experimental, work-in-progress).
  Ninja                        = Generates build.ninja files.
  Watcom WMake                 = Generates Watcom WMake makefiles.
  CodeBlocks - MinGW Makefiles = Generates CodeBlocks project files.
  CodeBlocks - NMake Makefiles = Generates CodeBlocks project files.
  CodeBlocks - NMake Makefiles JOM
                               = Generates CodeBlocks project files.
  CodeBlocks - Ninja           = Generates CodeBlocks project files.
  CodeBlocks - Unix Makefiles  = Generates CodeBlocks project files.
  CodeLite - MinGW Makefiles   = Generates CodeLite project files.
  CodeLite - NMake Makefiles   = Generates CodeLite project files.
  CodeLite - Ninja             = Generates CodeLite project files.
  CodeLite - Unix Makefiles    = Generates CodeLite project files.
  Sublime Text 2 - MinGW Makefiles
                               = Generates Sublime Text 2 project files.
  Sublime Text 2 - NMake Makefiles
                               = Generates Sublime Text 2 project files.
  Sublime Text 2 - Ninja       = Generates Sublime Text 2 project files.
  Sublime Text 2 - Unix Makefiles
                               = Generates Sublime Text 2 project files.
  Kate - MinGW Makefiles       = Generates Kate project files.
  Kate - NMake Makefiles       = Generates Kate project files.
  Kate - Ninja                 = Generates Kate project files.
  Kate - Unix Makefiles        = Generates Kate project files.
  Eclipse CDT4 - NMake Makefiles
                               = Generates Eclipse CDT 4.0 project files.
  Eclipse CDT4 - MinGW Makefiles
                               = Generates Eclipse CDT 4.0 project files.
  Eclipse CDT4 - Ninja         = Generates Eclipse CDT 4.0 project files.
  Eclipse CDT4 - Unix Makefiles= Generates Eclipse CDT 4.0 project files.

Traceback (most recent call last):
  File "build-workspace.py", line 98, in <module>
    run('cmake .. -G "Visual Studio 17 2022" -DVMPC2000XL_WIN7=1')
  File "build-workspace.py", line 35, in run
    raise Exception("Command failed: %s" % cmd)
Exception: Command failed: cmake .. -G "Visual Studio 17 2022" -DVMPC2000XL_WIN7=1

```

**Comment by izzyreal** [comment]
Which version of CMake you got? Any chance you can update it? Looks like you're close to a successful build otherwise.

**Comment by DruggedBunny** [comment]
That was it! I did need to update conan's profile -- slight tweak for anyone else is that I had to manually delete C:\Users\[username]\.conan\profiles\default due to an error message (profile already exists, I think), and that got me the project.

VS then crashes while trying to build via the IDE, which isn't helpful, especially as it doesn't give any clues as to what's wrong, but that's clearly VS's problem -- I'll try building from command line later, just been on a lunch break.

Will report back with the results! Thanks again, much appreciated.

**Comment by izzyreal** [comment]
Awesome you got it to build!

I tried the VST3 a while back with Reaper 6 and it worked: https://github.com/izzyreal/vmpc-juce/blob/master/plugin-compatibility-matrix.md But it may have been in the time that VMPC2000XL was registering itself as an effects processor rather than an instrument. I'll have to revisit Reaper compatibility in the near future. I created a ticket for this here: https://github.com/izzyreal/vmpc-juce/issues/51 Feel free to amend with comments if you want to, but hopefully I can pick this up in the near future.

For sound file locations see the docs here: https://vmpcdocs.izmar.nl/install.html#id8

When building from source the demo sounds, programs and sequences are not included. You can grab them from here https://github.com/izzyreal/vmpc-installer-scripts/tree/master/demo_data

**Comment by DruggedBunny** [comment]
You got it to build, ha ha.

Yeah, it just doesn't show in Reaper 6 after I think being detected, so seems to be silently filtered out by Reaper's checks -- there's no visible crash.

Thanks for the pointers -- I did grab the manual but yet to get stuck in so that helps, hadn't fully grasped I need to stick sounds in real folders... I'll play with the executable later anyway.

Sorry, did wonder if I'd closed off a bit early!

Thanks again.

**Comment by izzyreal** [comment]
No worries at all!
